# Site settings
email: your-email@domain.com
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://new.thebran.ch" # the base hostname & protocol for your site

name: The Branch
markdown: kramdown
kramdown:
  parse_block_html: true
permalink: /articles/:title
exclude: ['.gitignore', 'thebranch.sublime-project', 'thebranch.sublime-workspace', '/assets/.sass_cache', '/assets/node_modules', '/assets/gulpfile.js', '/assets/src', '/assets/package.json', '.git', '.gitignore', 'temp', '/assets/report', '/assets/reports']
include: ['.htaccess']
encoding: utf-8
destination: 'public_html'
description: 'A description goes here'